import { Bot, FileCode, Clock, Link as LinkIcon, ListOrdered, HardDrive, CreditCard, ArrowDownAZ, ArrowLeftRight, Calculator, CaseSensitive, Ruler, QrCode, KeyRound, HeartPulse, Cake, Image, FileText, Info, MessageSquare, Pencil, Pilcrow, Type, Banknote, Globe, FileImage, Palette, Youtube, ShieldCheck, Tags, TerminalSquare, Layers, Video, Pipette, Sheet, Table, Timer, Lock, Database, Binary, Code, Share2, Ratio, Scaling, CodeXml, Keyboard, Calendar, Smile, Search, GitCompareArrows, Users, Languages, Shuffle, Scroll, Braces, Voicemail, Eraser, ArrowDownUp, BarChart, Gift, FileSearch, Combine, Minimize, Merge, Split, ListChecks, BookOpen, BarChart2, FileCog, Wand2, RefreshCw, Hash, Dna, ScanSearch, Sparkles, Trash2, FlipHorizontal, Ghost, Repeat, Mail, Ban, Phone, TrendingUp, TrendingDown, ListX, XCircle, PenTool } from "lucide-react";

export const tools = [
  {
    icon: <Code className="h-8 w-8" />,
    href: "/regex-tester",
    title: "Regex Tester",
    description: "Test and validate Regular Expressions online with match results.",
  },
  {
    icon: <CaseSensitive className="h-8 w-8" />,
    href: "/case-converter",
    title: "Case Converter",
    description: "Convert text to UPPERCASE, lowercase, Sentence case, etc.",
  },
  {
    icon: <Wand2 className="h-8 w-8" />,
    href: "/ai-summarizer",
    title: "AI Summarizer (PDF/Text)",
    description: "Summarize PDF, DOC, or Text with AI. Translate, export, and analyze content.",
  },
  {
    icon: <PenTool className="h-8 w-8" />,
    href: "/sentence-rewriter",
    title: "Sentence Rewriter",
    description: "Automatically rewrite text by replacing words with synonyms.",
  },
  {
    icon: <Wand2 className="h-8 w-8" />,
    href: "/synonym-enhancer",
    title: "Synonym Enhancer",
    description: "Enhance your sentences by replacing words with better synonyms.",
  },
  {
    icon: <Languages className="h-8 w-8" />,
    href: "/foreign-word-detector",
    title: "Foreign Word Detector",
    description: "Detect foreign or non-English words inside English paragraphs.",
  },
  {
    icon: <RefreshCw className="h-8 w-8" />,
    href: "/text-case-toggler",
    title: "Text Case Toggler",
    description: "Toggle uppercase and lowercase letters in your text easily.",
  },
  {
    icon: <Type className="h-8 w-8" />,
    href: "/uppercase-counter",
    title: "Uppercase Counter",
    description: "Count how many words are written in ALL CAPS in your text.",
  },
  {
    icon: <Type className="h-8 w-8" />,
    href: "/title-capitalization",
    title: "Title Capitalization",
    description: "Convert text into grammatically correct Title Case.",
  },
  {
    icon: <Calculator className="h-8 w-8" />,
    href: "/sentence-counter",
    title: "Sentence Counter",
    description: "Count how many sentences your content contains.",
  },
  {
    icon: <BarChart2 className="h-8 w-8" />,
    href: "/word-frequency-counter",
    title: "Word Frequency Counter",
    description: "See which words are repeated the most in your text.",
  },
  {
    icon: <QrCode className="h-8 w-8" />,
    href: "/qr-generator-scanner",
    title: "QR Generator & Scanner",
    description: "Create & scan QR codes in seconds.",
  },
  {
    icon: <Palette className="h-8 w-8" />,
    href: "/color-converter",
    title: "Color Converter",
    description: "HEX ⇄ RGB ⇄ HSL converter with preview.",
  },
  {
    icon: <Hash className="h-8 w-8" />,
    href: "/hashtag-generator",
    title: "Hashtag Generator",
    description: "Generate hashtags from your content to increase reach.",
  },
  {
    icon: <Dna className="h-8 w-8" />,
    href: "/random-string-generator",
    title: "Random String Generator",
    description: "Generate a secure random string of customizable length.",
  },
  {
    icon: <Shuffle className="h-8 w-8" />,
    href: "/text-scrambler",
    title: "Text Scrambler",
    description: "Randomly shuffle characters or words in your text.",
  },
  {
    icon: <ScanSearch className="h-8 w-8" />,
    href: "/entity-extractor",
    title: "Entity Extractor",
    description: "Automatically detect emails, names, phones, dates, and more.",
  },
  {
    icon: <Sparkles className="h-8 w-8" />,
    href: "/whitespace-cleaner",
    title: "Whitespace Cleaner",
    description: "Clean up your text by removing extra spaces, tabs, and empty lines.",
  },
  {
    icon: <Trash2 className="h-8 w-8" />,
    href: "/duplicate-word-remover",
    title: "Duplicate Word Remover",
    description: "Clean your text by removing repeated words automatically.",
  },
  {
    icon: <FlipHorizontal className="h-8 w-8" />,
    href: "/text-mirror",
    title: "Text Mirror",
    description: "Flip every line of your text horizontally with this mirror effect tool.",
  },
  {
    icon: <Ghost className="h-8 w-8" />,
    href: "/invisible-character-detector",
    title: "Invisible Character Detector",
    description: "Find hidden characters like zero-width space, ZWNJ, and others.",
  },
  {
    icon: <Ruler className="h-8 w-8" />,
    href: "/text-width-estimator",
    title: "Text Width Estimator",
    description: "Estimate pixel width of text with font and size.",
  },
  {
    icon: <Repeat className="h-8 w-8" />,
    href: "/palindrome-checker",
    title: "Palindrome Checker",
    description: "Test whether your sentence is a palindrome.",
  },
  {
    icon: <Mail className="h-8 w-8" />,
    href: "/email-extractor",
    title: "Email Extractor",
    description: "Extract all email addresses from pasted text easily.",
  },
  {
    icon: <Ban className="h-8 w-8" />,
    href: "/emoji-remover",
    title: "Emoji Remover",
    description: "Strip all emojis from your input text instantly.",
  },
  {
    icon: <Type className="h-8 w-8" />,
    href: "/remove-diacritics",
    title: "Remove Diacritics",
    description: "Strip accents and special characters from your text easily.",
  },
  {
    icon: <Smile className="h-8 w-8" />,
    href: "/emoji-replacer",
    title: "Emoji Replacer",
    description: "Replace common words with emojis to make your text fun.",
  },
  {
    icon: <Phone className="h-8 w-8" />,
    href: "/phone-number-extractor",
    title: "Phone Number Extractor",
    description: "Extract phone numbers from any block of text quickly.",
  },
  {
    icon: <TrendingUp className="h-8 w-8" />,
    href: "/ultra-percent-calculator",
    title: "Ultra % Calculator",
    description: "Increase, Reverse, CAGR, Discount, Tax.",
  },
  {
    icon: <Sheet className="h-8 w-8" />,
    href: "/json-to-csv",
    title: "JSON to CSV",
    description: "Convert JSON data to CSV format quickly.",
  },
  {
    icon: <ListX className="h-8 w-8" />,
    href: "/remove-duplicate-lines",
    title: "Remove Duplicate Lines",
    description: "Eliminate duplicate lines from a text block.",
  },
  {
    icon: <LinkIcon className="h-8 w-8" />,
    href: "/text-to-slug",
    title: "Text to Slug Converter",
    description: "Convert your titles or strings into slugs.",
  },
  {
    icon: <XCircle className="h-8 w-8" />,
    href: "/remove-symbols",
    title: "Remove Symbols",
    description: "Strip all symbols from your input text.",
  },
  {
    icon: <Binary className="h-8 w-8" />,
    href: "/text-to-ascii",
    title: "Text to ASCII",
    description: "Convert regular text into ASCII codes.",
  },
  {
    icon: <CreditCard className="h-8 w-8" />,
    href: "/cvv-to-json",
    title: "CVV to JSON",
    description: "Convert card CVV data into JSON structure format.",
  },
  {
    icon: <Binary className="h-8 w-8" />,
    href: "/extract-numbers",
    title: "Extract Numbers",
    description: "Extract only numbers from a block of text.",
  },
  {
    icon: <Eraser className="h-8 w-8" />,
    href: "/remove-blank-lines",
    title: "Remove Blank Lines",
    description: "Remove all blank lines from your text.",
  },
  {
    icon: <ArrowDownAZ className="h-8 w-8" />,
    href: "/sort-lines",
    title: "Sort Lines Alphabetically",
    description: "Sort your text lines from A to Z.",
  },
  {
    icon: <ArrowLeftRight className="h-8 w-8" />,
    href: "/reverse-text",
    title: "Reverse Text",
    description: "Reverse the content of your text easily.",
  },
  {
    icon: <ListOrdered className="h-8 w-8" />,
    href: "/list-generator",
    title: "List Generator",
    description: "Create custom number lists by specifying start, end, and step.",
  },
  {
    icon: <Type className="h-8 w-8" />,
    href: "/number-to-words",
    title: "Number to Words",
    description: "Convert numbers into written English words instantly.",
  },
  {
    icon: <HardDrive className="h-8 w-8" />,
    href: "/file-size-converter",
    title: "File Size Converter",
    description: "Convert between B, KB, MB, GB accurately.",
  },
  {
    icon: <Bot className="h-8 w-8" />,
    href: "/chatbot-ai",
    title: "ChatBot AI",
    description: "Advanced AI chatbot that understands and responds naturally.",
  },
  {
    icon: <FileCode className="h-8 w-8" />,
    href: "/javascript-minifier",
    title: "JavaScript Minifier",
    description: "Minify and compress your JavaScript code for better performance.",
  },
  {
    icon: <Lock className="h-8 w-8" />,
    href: "/base64-encoder-decoder",
    title: "Base64 Encoder/Decoder",
    description: "Encode text to Base64 or decode it back to plain text.",
  },
  {
    icon: <LinkIcon className="h-8 w-8" />,
    href: "/url-encoder-decoder",
    title: "URL Encoder/Decoder",
    description: "Encode or decode URLs safely.",
  },
  {
    icon: <Clock className="h-8 w-8" />,
    href: "/timestamp-converter",
    title: "Timestamp Converter",
    description: "Convert timestamps to readable date/time.",
  },
  {
    icon: <Wand2 className="h-8 w-8" />,
    href: "/text-summarizer",
    title: "AI Text Summarizer",
    description: "Summarize any paragraph or article to just a few key sentences.",
  },
  {
    icon: <Braces className="h-8 w-8" />,
    href: "/json-formatter",
    title: "JSON Formatter",
    description: "Format, validate, and beautify your JSON data instantly.",
  },
  {
    icon: <Palette className="h-8 w-8" />,
    href: "/css-minifier",
    title: "CSS Minifier",
    description: "Minify CSS to reduce file size and improve load times.",
  },
  {
    icon: <BookOpen className="h-8 w-8" />,
    href: "/flipbook-maker",
    title: "Flipbook Maker",
    description: "Convert a PDF into an interactive flipbook with page-turning effects.",
  },
  {
    icon: <Gift className="h-8 w-8" />,
    href: "/random-picker-wheel",
    title: "Random Picker Wheel",
    description: "Spin a virtual wheel to randomly select a winner from a list of options.",
  },
  {
    icon: <ListChecks className="h-8 w-8" />,
    href: "/random-item-picker",
    title: "Random Item Picker",
    description: "Enter a list of items and let the tool randomly pick one for you.",
  },
  {
    icon: <FileText className="h-8 w-8" />,
    href: "/resume-builder",
    title: "Resume Builder",
    description: "Create and customize professional resumes with a live preview.",
  },
  {
    icon: <Merge className="h-8 w-8" />,
    href: "/pdf-merger",
    title: "PDF Merger",
    description: "Combine multiple PDF files into one single document.",
  },
  {
    icon: <Split className="h-8 w-8" />,
    href: "/pdf-splitter",
    title: "PDF Splitter",
    description: "Split a single PDF into multiple smaller documents by page range.",
  },
  {
    icon: <Minimize className="h-8 w-8" />,
    href: "/image-compressor",
    title: "Image Compressor",
    description: "Compress JPG, PNG, and WEBP images to reduce file size.",
  },
  {
    icon: <QrCode className="h-8 w-8" />,
    href: "/qr-code-generator",
    title: "QR Code Generator",
    description: "Create custom QR codes for URLs, text, WiFi, and more.",
  },
  {
    icon: <Combine className="h-8 w-8" />,
    href: "/paragraph-merger",
    title: "Paragraph Merger",
    description: "Merge multiple paragraphs into a single block of text.",
  },
  {
    icon: <CodeXml className="h-8 w-8" />,
    href: "/html-entity-decoder",
    title: "HTML Entity Decoder",
    description: "Encode and decode special HTML characters for safe web display.",
  },
  {
    icon: <FileSearch className="h-8 w-8" />,
    href: "/text-pattern-finder",
    title: "Text Pattern Finder (Regex)",
    description: "Search and highlight specific patterns or words using regular expressions.",
  },
  {
    icon: <BarChart className="h-8 w-8" />,
    href: "/word-density-analyzer",
    title: "Word Density Analyzer",
    description: "Analyze your text to see how many times each word appears.",
  },
  {
    icon: <ArrowDownUp className="h-8 w-8" />,
    href: "/number-sorter",
    title: "Number Sorter",
    description: "Sort a list of numbers in ascending or descending order.",
  },
  {
    icon: <Eraser className="h-8 w-8" />,
    href: "/punctuation-remover",
    title: "Punctuation Remover",
    description: "Remove all punctuation marks from text with one click.",
  },
  {
    icon: <Voicemail className="h-8 w-8" />,
    href: "/vowel-consonant-counter",
    title: "Vowel & Consonant Counter",
    description: "Count the number of vowels and consonants in any text.",
  },
  {
    icon: <Braces className="h-8 w-8" />,
    href: "/json-validator",
    title: "JSON Validator",
    description: "Check if JSON data is valid and highlight errors directly in the browser.",
  },
  {
    icon: <Shuffle className="h-8 w-8" />,
    href: "/sentence-shuffler",
    title: "Sentence Shuffler",
    description: "Randomly shuffle sentences in a paragraph while keeping punctuation intact.",
  },
  {
    icon: <Shuffle className="h-8 w-8" />,
    href: "/anagram-finder",
    title: "Anagram Finder",
    description: "Find all possible letter combinations (permutations) for a given word.",
  },
  {
    icon: <Languages className="h-8 w-8" />,
    href: "/morse-code-translator",
    title: "Morse Code Translator",
    description: "Convert text to Morse code and back, with sound playback.",
  },
  {
    icon: <CaseSensitive className="h-8 w-8" />,
    href: "/text-tools",
    title: "Text Tools",
    description: "Manipulate text with tools for case conversion and more.",
  },
  {
    icon: <GitCompareArrows className="h-8 w-8" />,
    href: "/text-diff-highlighter",
    title: "Text Diff Highlighter",
    description: "Compare two blocks of text and highlight the differences.",
  },
  {
    icon: <Ruler className="h-8 w-8" />,
    href: "/unit-converter",
    title: "Unit Converter",
    description: "Convert between various units for length, mass, and temperature.",
  },
   {
    icon: <Banknote className="h-8 w-8" />,
    href: "/currency-converter",
    title: "Currency Converter",
    description: "Convert values between different world currencies.",
  },
  {
    icon: <Calculator className="h-8 w-8" />,
    href: "/calculator",
    title: "Calculator",
    description: "A simple and easy-to-use calculator for your daily needs.",
  },
  {
    icon: <Binary className="h-8 w-8" />,
    href: "/base-converter",
    title: "Base Converter",
    description: "Convert numbers between binary, octal, decimal, and hexadecimal.",
  },
  {
    icon: <Scroll className="h-8 w-8" />,
    href: "/roman-numeral-converter",
    title: "Roman Numeral Converter",
    description: "Convert numbers to Roman numerals and vice versa.",
  },
  {
    icon: <KeyRound className="h-8 w-8" />,
    href: "/password-generator",
    title: "Password Generator",
    description: "Generate strong, secure, and random passwords.",
  },
  {
    icon: <ShieldCheck className="h-8 w-8" />,
    href: "/password-strength-checker",
    title: "Password Strength Checker",
    description: "Test the strength of your password and get suggestions to make it more secure.",
  },
   {
    icon: <Users className="h-8 w-8" />,
    href: "/random-username-generator",
    title: "Random Username Generator",
    description: "Generate creative usernames from keywords and random words.",
  },
  {
    icon: <Lock className="h-8 w-8" />,
    href: "/text-encryption",
    title: "Text Encryption Tool",
    description: "Encrypt and decrypt text using a simple Caesar cipher.",
  },
  {
    icon: <Tags className="h-8 w-8" />,
    href: "/meta-tag-generator",
    title: "Meta Tag Generator",
    description: "Generate perfect SEO meta titles, descriptions, and keywords for your website.",
  },
  {
    icon: <Share2 className="h-8 w-8" />,
    href: "/open-graph-generator",
    title: "Open Graph Tag Generator",
    description: "Generate perfect Open Graph meta tags for better link previews on social media.",
  },
  {
    icon: <Table className="h-8 w-8" />,
    href: "/html-table-generator",
    title: "HTML Table Generator",
    description: "Create clean HTML table code from row and column inputs.",
  },
   {
    icon: <Code className="h-8 w-8" />,
    href: "/html-minifier",
    title: "HTML Minifier",
    description: "Minify HTML code by removing spaces, line breaks, and comments.",
  },
  {
    icon: <Layers className="h-8 w-8" />,
    href: "/css-box-shadow-generator",
    title: "CSS Box Shadow Generator",
    description: "Visually design CSS box shadows and copy the generated code instantly.",
  },
  {
    icon: <Pipette className="h-8 w-8" />,
    href: "/css-gradient-generator",
    title: "CSS Gradient Generator",
    description: "Create custom linear and radial gradients with a color picker and copy the CSS.",
  },
  {
    icon: <Sheet className="h-8 w-8" />,
    href: "/csv-viewer",
    title: "CSV Viewer",
    description: "Upload a CSV file and view it in a clean, sortable, and searchable table.",
  },
  {
    icon: <Table className="h-8 w-8" />,
    href: "/table-to-csv-converter",
    title: "Table to CSV Converter",
    description: "Convert any HTML table into a downloadable CSV file.",
  },
  {
    icon: <HeartPulse className="h-8 w-8" />,
    href: "/bmi-calculator",
    title: "BMI Calculator",
    description: "Calculate your Body Mass Index to assess your weight status.",
  },
  {
    icon: <Cake className="h-8 w-8" />,
    href: "/age-calculator",
    title: "Age Calculator",
    description: "Find out your exact age in years, months, and days.",
  },
  {
    icon: <Calendar className="h-8 w-8" />,
    href: "/date-difference-calculator",
    title: "Date Difference Calculator",
    description: "Calculate the number of days, weeks, or months between two dates.",
  },
   {
    icon: <Ratio className="h-8 w-8" />,
    href: "/aspect-ratio-calculator",
    title: "Aspect Ratio Calculator",
    description: "Calculate correct dimensions while maintaining an image’s aspect ratio.",
  },
  {
    icon: <Scaling className="h-8 w-8" />,
    href: "/px-to-rem-converter",
    title: "Pixel to Rem Converter",
    description: "Convert pixel values to rem and vice versa for responsive web design.",
  },
  {
    icon: <Timer className="h-8 w-8" />,
    href: "/stopwatch-timer",
    title: "Stopwatch & Timer",
    description: "A responsive stopwatch and countdown timer that works offline."
  },
  {
    icon: <Keyboard className="h-8 w-8" />,
    href: "/keyboard-event-tester",
    title: "Keyboard Event Tester",
    description: "Detect and display key codes and key names when you press any key.",
  },
  {
    icon: <Image className="h-8 w-8" />,
    href: "/image-converter",
    title: "Image Converter",
    description: "Easily convert image files between PNG, JPG, and WEBP formats.",
  },
  {
    icon: <FileImage className="h-8 w-8" />,
    href: "/image-to-pdf-converter",
    title: "Image to PDF Converter",
    description: "Convert multiple images (JPG, PNG, WebP) into a single PDF file.",
  },
   {
    icon: <Pencil className="h-8 w-8" />,
    href: "/notepad",
    title: "Notepad",
    description: "A simple notepad to write, edit, save locally, and download your notes.",
  },
  {
    icon: <Pilcrow className="h-8 w-8" />,
    href: "/rich-text-editor",
    title: "Rich Text Editor",
    description: "An advanced editor for formatted text with headings, lists, and more.",
  },
   {
    icon: <TerminalSquare className="h-8 w-8" />,
    href: "/markdown-editor",
    title: "Markdown Editor",
    description: "A live Markdown editor that shows instant preview of formatted text.",
  },
  {
    icon: <Type className="h-8 w-8" />,
    href: "/word-counter",
    title: "Word & Character Counter",
    description: "Count words, characters, sentences, and paragraphs in your text.",
  },
  {
    icon: <Pilcrow className="h-8 w-8" />,
    href: "/lorem-ipsum-generator",
    title: "Lorem Ipsum Generator",
    description: "Generate random placeholder text with an exact number of words.",
  },
  {
    icon: <Smile className="h-8 w-8" />,
    href: "/random-emoji-generator",
    title: "Random Emoji Generator",
    description: "Generate a random emoji or emoji set instantly.",
  },
  {
    icon: <Globe className="h-8 w-8" />,
    href: "/time-zone-converter",
    title: "Time Zone Converter",
    description: "Compare the current time across different parts of the world.",
  },
  {
    icon: <Globe className="h-8 w-8" />,
    href: "/ip-address-finder",
    title: "IP Address Finder",
    description: "Display your public IP address using a free API.",
  },
  {
    icon: <Palette className="h-8 w-8" />,
    href: "/color-picker",
    title: "Color Picker",
    description: "Pick a color and get its HEX, RGB, and HSL codes for your projects.",
  },
  {
    icon: <Database className="h-8 w-8" />,
    href: "/local-storage-editor",
    title: "Local Storage Editor",
    description: "View, edit, and delete data stored in your browser's local storage.",
  },
  {
    icon: <Info className="h-8 w-8" />,
    href: "/about",
    title: "About",
    description: "Learn more about our mission and the creator of this website.",
  },
  {
    icon: <MessageSquare className="h-8 w-8" />,
    href: "/contact",
    title: "Contact",
    description: "Get in touch with us for questions, feedback, or suggestions.",
  },
];

export const guides = [
  {
    icon: <Braces className="h-8 w-8 text-primary" />,
    href: "/guide#json-formatter",
    title: "JSON Formatter Guide",
    description: "How to use the JSON Formatter tool.",
    steps: [
        "Navigate to the JSON Formatter page.",
        "Paste your raw JSON into the 'Input JSON' text area.",
        "Click the 'Prettify' button to format the JSON with proper indentation.",
        "Click the 'Minify' button to remove all whitespace and compress the JSON.",
        "The result will appear in the 'Formatted JSON' area, ready to be copied."
    ]
  },
  {
    icon: <Wand2 className="h-8 w-8 text-primary" />,
    href: "/guide#text-summarizer",
    title: "Text Summarizer Guide",
    description: "How to use the AI Text Summarizer.",
    steps: [
        "Go to the Text Summarizer tool.",
        "Paste your long text, article, or document into the text area.",
        "Click 'Summarize' to let the AI process the content.",
        "Review the generated summary which captures the key points.",
        "Copy the summary for your use."
    ]
  },
  {
    icon: <FileImage className="h-8 w-8 text-primary" />,
    href: "/guide#image-to-pdf",
    title: "Image to PDF Guide",
    description: "Convert images to PDF documents.",
    steps: [
        "Select the Image to PDF Converter tool.",
        "Upload one or more images (JPG, PNG, WebP).",
        "Arrange the images in the desired order if needed.",
        "Click 'Convert to PDF' to generate the document.",
        "Download the resulting PDF file."
    ]
  }
];
